app:
  name: auth
  secret: 63c15ef2f4b8ae0e9c9f8761b6063ef166681597
db:
  adapter: postgresql
  host: localhost
  user: postgres
  url: <%= ENV['ADS_DATABASE_URL'] %>
pagination:
  page_size: 10
rabbit_mq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD'] %> 
  consumers_pool: 10
logger:
  path: log/app.log
  level: info